before_script:
- python3 -V

stages:
- restore-packages
- build
- deploy

restore-pip-packages:
    tags:
    - graph-analytica
    stage: restore-packages
    script:
    - pip3 install -r requirements.txt

build:
    tags:
    - graph-analytica
    stage: build
    script:
    - npm install
    - npm run build-prod
    - npm run test-prod
    artifacts:
        paths:
        - dist/ coverage/*
    coverage: '/(\d*.?\d+)%/'
deploy:
    tags:
    - graph-analytica
    stage: deploy
    dependencies:
    - build
    environment:
        name: production
        url: http://graphanalytica.tk
    only:
    - master
    artifacts:
        paths:
        - graphanalytica core
    script:
    - python3 manage.py collectstatic --noinput
    - sudo cp -r static/ graphanalytica/ core/ /var/www/graphanalytica/
