variables:
  #POSTGRES_DB: database_name

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/


# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  # Print out python version for debugging
    - python3 -V
    #- apt-get update -q && apt-get install nodejs -yqq

stages:
    - restore-packages
    - build
    - deploy

job restore-packages:
    tags:
        - graph-analytica
    stage: restore-packages
    script:
        - pip3 install -r requirements.txt
        - npm install

job build:
    tags:
        - graph-analytica
    stage: build
    script:
        - ng build --prod
        - python3 manage.py collectstatic
