before_script:
- python3 -V

stages:
- restore-packages
- build
- test
- deploy

restore:pip:
    tags:
    - graph-analytica
    stage: restore-packages
    script:
    - pip3 install -r requirements.txt

restore:npm:
    tags:
    - graph-analytica
    cache:
        key: node_packages
        policy: push
        paths:
        - node_modules/
    stage: restore-packages
    script:
    - npm install

build:
    tags:
    - graph-analytica
    stage: build
    cache:
        key: node_packages
        policy: pull
        paths:
        - node_modules/
    script:
    - npm run build-prod
    artifacts:
        paths:
        - dist/

test:frontend:
    tags:
    - graph-analytica
    cache:
        key: node_packages
        policy: pull
        paths:
        - node_modules/
    stage: test
    script:
    - npm run test-prod
    artifacts:
        paths:
        - coverage/*
    coverage: '/(\d*.?\d+)%/'
deploy:
    tags:
    - graph-analytica
    stage: deploy
    dependencies:
    - build
    environment:
        name: production
        url: http://graphanalytica.tk
    only:
    - master
    artifacts:
        paths:
        - graphanalytica core
    script:
    - python3 manage.py collectstatic --noinput
    - sudo cp -r static/ graphanalytica/ core/ /var/www/graphanalytica/
