variables:
#POSTGRES_DB: database_name

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache



# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
# Print out python version for debugging
- python3 -V
#- apt-get update -q && apt-get install nodejs -yqq

stages:
- process-frontend
- process-backend
- deploy


job process-frontend:
    tags:
    - graph-analytica
    stage: process-frontend
    script:
    - npm install
    - npm run build-prod
    cache:
        key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
        policy: push
        paths:
        - dist/

job process-backend:
    tags:
    - graph-analytica
    stage: process-backend
    cache:
        key: "$CI_BUILD_REF_NAME"
        policy: pull
        paths:
        - dist/
    script:
    - pip3 install -r requirements.txt
    - python3 manage.py collectstatic --noinput
