variables:
  #POSTGRES_DB: database_name

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
    paths:
        - ~/.cache/pip/

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
tags:
    - graph-analytica

before_script:
  # Print out python version for debugging
    - python3 -V
    #- apt-get update -q && apt-get install nodejs -yqq

stages:
    - restore-packages
    - build
    - deploy

job restore-packages:
    stage: restore-packages
    script:
        - pip3 install -r requirements.txt
        - npm install

job build:
    stage: build
        script:
            - ng build --prod
            - python3 manage.py collectstatic
